services:
  database:
    image: pgvector/pgvector:pg16
    container_name: shop-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      TZ: ${DATABASE_TZ}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: shop-redis
    restart: unless-stopped
    command: [ "redis-server", "--appendonly", "yes", "--requirepass", "${REDIS_PASSWORD}" ]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  redis-ui:
    image: rediscommander/redis-commander:latest
    container_name: shop-redis-ui
    restart: unless-stopped
    depends_on:
      - redis
    environment:
      REDIS_HOSTS: "local:redis:6379:0:${REDIS_PASSWORD}"
    ports:
      - "8081:8081"

volumes:
  postgres_data:
  redis_data:
