services:
  database:
    image: pgvector/pgvector:pg16
    container_name: shop-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      TZ: ${DATABASE_TZ}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: shop-redis
    restart: unless-stopped
    command: [ "redis-server", "--appendonly", "yes", "--requirepass", "${REDIS_PASSWORD}" ]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  redis-ui:
    image: rediscommander/redis-commander:latest
    container_name: shop-redis-ui
    restart: unless-stopped
    depends_on:
      - redis
    environment:
      REDIS_HOSTS: "local:redis:6379:0:${REDIS_PASSWORD}"
    ports:
      - "8081:8081"

  minio:
    image: quay.io/minio/minio
    container_name: shop-minio
    restart: unless-stopped
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  minio-init:
    image: minio/mc:latest
    container_name: shop-minio-init
    depends_on:
      - minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_BUCKET: shop
    entrypoint: >
      /bin/sh -c "
      until mc alias set local http://minio:9000
      \"$${MINIO_ROOT_USER}\"
      \"$${MINIO_ROOT_PASSWORD}\";
      do
        sleep 1;
      done;
      
      mc ready local;
      
      mc mb --ignore-existing local/$${MINIO_BUCKET};
      
      mc anonymous set download local/$${MINIO_BUCKET};
      "

volumes:
  postgres_data:
  redis_data:
  minio_data:
